import datetime
from typing import Any, Dict, List


BANNED_USERS: List[str]
DATABASE_CLASS: str
DATABASE_FILE: str
DETECTLANGUAGE_API_KEY: str
INCLUDE_MENTIONS: bool
MEGAHAL_API: Dict[str, Any]
POST_STATUS_LIMIT_RESET_FREQUENCY: int
POST_STATUS_LIMIT: int
RANDOM_POST_TIMES: List[datetime.time]
RUNNER_SLEEP_SECONDS: int
SCREEN_NAME: str
TWITTER_API: Dict[str, Any]
USE_REDIS: bool
