from argparse import ArgumentParser, Namespace, _MutuallyExclusiveGroup
from types import ModuleType
from typing import Any, Dict, Generic, Type, TypeVar, Union

import twitterhal


TH = TypeVar("TH", bound=twitterhal.TwitterHAL)


def main(): ...

class CommandLine(Generic[TH]):
    args: Namespace
    hal: TH
    mutex: _MutuallyExclusiveGroup
    parser: ArgumentParser
    TwitterHAL: Type[TH]

    def __enter__(self): ...
    def __exit__(self, *args, **kwargs): ...
    def __init__(self, twitterhal_class: Type[TH], settings_module=Union[str, ModuleType, None]): ...
    def get_hal_kwargs(self) -> Dict[str, Any]: ...
    def print_stats(self): ...
    def run_extra(self, *args, **kwargs) -> bool: ...
    def run(self, *args, **kwargs): ...
    def setup(self, *args, **kwargs): ...
