import datetime
from typing import Any, List, Pattern


emoji_pattern: Pattern[str]
hashtag_pattern: Pattern[str]
url_pattern: Pattern[str]


def camel_case(string: str) -> str: ...
def parse_time_string_list(string: str) -> List[datetime.time]: ...
def print_r(obj: Any, name: str, indent: int): ...
def size_r(obj: Any) -> int: ...
def slice_to_redis_range(slice_: slice) -> range: ...
def strip_phrase(phrase: str) -> str: ...
